/* Capital city coordinates [lon, lat], from Natural Earth's 10m populated
   places (public domain). Generated by scripts/fetch-capitals.mjs. */

export const CAPITALS = {
  AF: [69.181, 34.519], // Kabul
  AL: [19.819, 41.328], // Tirana
  DZ: [3.049, 36.765], // Algiers
  AD: [1.527, 42.511], // Andorra
  AO: [13.232, -8.836], // Luanda
  AG: [-61.850, 17.118], // Saint John's
  AR: [-58.433, -34.611], // Buenos Aires
  AM: [44.512, 40.183], // Yerevan
  AU: [149.129, -35.283], // Canberra
  AT: [16.365, 48.202], // Vienna
  AZ: [49.860, 40.397], // Baku
  BS: [-77.350, 25.083], // Nassau
  BH: [50.583, 26.236], // Manama
  BD: [90.407, 23.725], // Dhaka
  BB: [-59.617, 13.102], // Bridgetown
  BY: [27.565, 53.902], // Minsk
  BE: [4.331, 50.835], // Brussels
  BZ: [-88.767, 17.252], // Belmopan
  BJ: [2.617, 6.483], // Porto-Novo
  BT: [89.639, 27.473], // Thimphu
  BO: [-65.260, -19.041], // Sucre
  BA: [18.383, 43.850], // Sarajevo
  BW: [25.912, -24.646], // Gaborone
  BR: [-47.918, -15.781], // Brasília
  BN: [114.933, 4.883], // Bandar Seri Begawan
  BG: [23.315, 42.685], // Sofia
  BF: [-1.527, 12.372], // Ouagadougou
  BI: [29.844, -3.426], // Gitega
  KH: [104.915, 11.552], // Phnom Penh
  CM: [11.515, 3.869], // Yaoundé
  CA: [-75.702, 45.419], // Ottawa
  CV: [-23.517, 14.917], // Praia
  CF: [18.558, 4.367], // Bangui
  TD: [15.047, 12.115], // N'Djamena
  CL: [-70.651, -33.440], // Santiago
  CN: [116.394, 39.902], // Beijing
  CO: [-74.085, 4.598], // Bogota
  KM: [43.240, -11.704], // Moroni
  CG: [15.283, -4.257], // Brazzaville
  CR: [-84.079, 9.930], // San José
  HR: [16.000, 45.800], // Zagreb
  CU: [-82.366, 23.134], // Havana
  CY: [33.367, 35.167], // Nicosia
  CZ: [14.423, 50.087], // Prague
  CD: [15.313, -4.328], // Kinshasa
  DK: [12.562, 55.681], // København
  DJ: [43.148, 11.595], // Djibouti
  DM: [-61.387, 15.301], // Roseau
  DO: [-69.930, 18.471], // Santo Domingo
  EC: [-78.502, -0.213], // Quito
  EG: [31.248, 30.052], // Cairo
  SV: [-89.216, 13.703], // San Salvador
  GQ: [8.783, 3.750], // Malabo
  ER: [38.933, 15.333], // Asmara
  EE: [24.728, 59.434], // Tallinn
  SZ: [31.200, -26.467], // Lobamba
  ET: [38.698, 9.035], // Addis Ababa
  FJ: [178.442, -18.133], // Suva
  FI: [24.932, 60.164], // Helsinki
  FR: [2.353, 48.858], // Paris
  GA: [9.458, 0.385], // Libreville
  GM: [-16.592, 13.454], // Banjul
  GE: [44.789, 41.727], // Tbilisi
  DE: [13.400, 52.524], // Berlin
  GH: [-0.219, 5.552], // Accra
  GR: [23.731, 37.985], // Athens
  GD: [-61.742, 12.053], // Saint George's
  GT: [-90.529, 14.623], // Guatemala City
  GN: [-13.682, 9.533], // Conakry
  GW: [-15.598, 11.865], // Bissau
  GY: [-58.167, 6.802], // Georgetown
  HT: [-72.338, 18.543], // Port-au-Prince
  HN: [-87.219, 14.104], // Tegucigalpa
  HU: [19.081, 47.502], // Budapest
  IS: [-21.937, 64.143], // Reykjavík
  IN: [77.200, 28.600], // New Delhi
  ID: [106.827, -6.172], // Jakarta
  IR: [51.422, 35.674], // Tehran
  IQ: [44.392, 33.341], // Baghdad
  IE: [-6.257, 53.347], // Dublin
  IL: [35.207, 31.778], // Jerusalem
  IT: [12.481, 41.898], // Rome
  CI: [-5.276, 6.818], // Yamoussoukro
  JM: [-76.767, 17.977], // Kingston
  JP: [139.749, 35.687], // Tokyo
  JO: [35.931, 31.952], // Amman
  KZ: [71.428, 51.181], // Nur-Sultan
  KE: [36.815, -1.281], // Nairobi
  KI: [173.018, 1.338], // Tarawa
  KW: [47.976, 29.372], // Kuwait City
  KG: [74.583, 42.875], // Bishkek
  LA: [102.600, 17.967], // Vientiane
  LV: [24.100, 56.950], // Riga
  LB: [35.508, 33.874], // Beirut
  LS: [27.483, -29.317], // Maseru
  LR: [-10.800, 6.315], // Monrovia
  LY: [13.180, 32.892], // Tripoli
  LI: [9.517, 47.134], // Vaduz
  LT: [25.317, 54.683], // Vilnius
  LU: [6.130, 49.612], // Luxembourg
  MG: [47.515, -18.915], // Antananarivo
  MW: [33.783, -13.983], // Lilongwe
  MY: [101.689, 3.140], // Kuala Lumpur
  MV: [73.509, 4.172], // Malé
  ML: [-8.002, 12.652], // Bamako
  MT: [14.515, 35.900], // Valletta
  MH: [171.380, 7.103], // Majuro
  MR: [-15.975, 18.086], // Nouakchott
  MU: [57.500, -20.167], // Port Louis
  MX: [-99.133, 19.444], // Mexico City
  FM: [158.150, 6.917], // Palikir
  MD: [28.858, 47.005], // Chișinău
  MC: [7.407, 43.740], // Monaco
  MN: [106.915, 47.919], // Ulaanbaatar
  ME: [19.266, 42.466], // Podgorica
  MA: [-6.836, 34.025], // Rabat
  MZ: [32.587, -25.953], // Maputo
  MM: [96.117, 19.769], // Naypyidaw
  NA: [17.084, -22.570], // Windhoek
  NR: [166.921, -0.548], // Yaren (manual)
  NP: [85.315, 27.719], // Kathmandu
  NL: [4.915, 52.352], // Amsterdam
  NZ: [174.777, -41.292], // Wellington
  NI: [-86.270, 12.155], // Managua
  NE: [7.096, 13.492], // Niamey
  NG: [7.490, 9.055], // Abuja
  KP: [125.753, 39.021], // Pyongyang
  MK: [21.433, 42.000], // Skopje
  NO: [10.748, 59.919], // Oslo
  OM: [58.378, 23.585], // Muscat
  PK: [73.081, 33.689], // Islamabad
  PW: [134.627, 7.487], // Melekeok
  PA: [-79.535, 8.970], // Panama City
  PG: [147.193, -9.465], // Port Moresby
  PY: [-57.626, -25.291], // Asunción
  PE: [-77.052, -12.046], // Lima
  PH: [120.980, 14.606], // Manila
  PL: [21.005, 52.231], // Warsaw
  PT: [-9.147, 38.725], // Lisbon
  QA: [51.533, 25.287], // Doha
  RO: [26.098, 44.435], // Bucharest
  RU: [37.614, 55.754], // Moscow
  RW: [30.059, -1.952], // Kigali
  KN: [-62.717, 17.302], // Basseterre
  LC: [-60.993, 14.008], // Castries
  VC: [-61.220, 13.156], // Kingstown
  WS: [-171.769, -13.836], // Apia
  SM: [12.442, 43.936], // San Marino
  SA: [46.720, 24.634], // Riyadh
  SN: [-17.475, 14.718], // Dakar
  RS: [20.466, 44.821], // Belgrade
  SC: [55.450, -4.617], // Victoria
  SL: [-13.236, 8.472], // Freetown
  SG: [103.854, 1.295], // Singapore
  SK: [17.117, 48.150], // Bratislava
  SI: [14.515, 46.055], // Ljubljana
  SB: [159.950, -9.438], // Honiara
  SO: [45.365, 2.069], // Mogadishu
  ZA: [28.227, -25.705], // Pretoria
  KR: [126.998, 37.568], // Seoul
  SS: [31.580, 4.830], // Juba
  ES: [-3.685, 40.402], // Madrid
  LK: [79.858, 6.932], // Colombo
  SD: [32.532, 15.590], // Khartoum
  SR: [-55.167, 5.835], // Paramaribo
  SE: [18.066, 59.324], // Stockholm
  CH: [7.467, 46.917], // Bern
  SY: [36.298, 33.502], // Damascus
  ST: [6.730, 0.337], // São Tomé
  TJ: [68.774, 38.560], // Dushanbe
  TZ: [35.750, -6.183], // Dodoma
  TH: [100.515, 13.752], // Bangkok
  TL: [125.579, -8.559], // Dili
  TG: [1.221, 6.134], // Lomé
  TO: [-175.221, -21.139], // Nuku'alofa
  TT: [-61.517, 10.652], // Port-of-Spain
  TN: [10.180, 36.803], // Tunis
  TM: [58.383, 37.950], // Ashgabat
  TV: [179.217, -8.517], // Funafuti
  TR: [32.862, 39.929], // Ankara
  UG: [32.581, 0.319], // Kampala
  UA: [30.515, 50.435], // Kyiv
  AE: [54.367, 24.467], // Abu Dhabi
  GB: [-0.119, 51.502], // London
  US: [-77.011, 38.901], // Washington,  D.C.
  UY: [-56.187, -34.905], // Montevideo
  UZ: [69.269, 41.304], // Tashkent
  VU: [168.317, -17.733], // Port Vila
  VA: [12.453, 41.903], // Vatican City
  VE: [-66.919, 10.503], // Caracas
  VN: [105.848, 21.035], // Hanoi
  YE: [44.205, 15.357], // Sanaa
  ZM: [28.281, -15.415], // Lusaka
  ZW: [31.043, -17.816], // Harare
};
