/* 195 UN member and observer states.
   Columns: ISO numeric (matches the world-atlas topology), ISO alpha-2,
   English name, English capital, continent, subregion, optional footnote. */

const EN = [
  ["004","AF","Afghanistan","Kabul","Asia","Southern Asia"],
  ["008","AL","Albania","Tirana","Europe","Southeast Europe"],
  ["012","DZ","Algeria","Algiers","Africa","Northern Africa"],
  ["020","AD","Andorra","Andorra la Vella","Europe","Southern Europe"],
  ["024","AO","Angola","Luanda","Africa","Middle Africa"],
  ["028","AG","Antigua and Barbuda","Saint John's","Americas","Caribbean"],
  ["032","AR","Argentina","Buenos Aires","Americas","South America"],
  ["051","AM","Armenia","Yerevan","Asia","Western Asia"],
  ["036","AU","Australia","Canberra","Oceania","Australia and New Zealand"],
  ["040","AT","Austria","Vienna","Europe","Central Europe"],
  ["031","AZ","Azerbaijan","Baku","Asia","Western Asia"],
  ["044","BS","Bahamas","Nassau","Americas","Caribbean"],
  ["048","BH","Bahrain","Manama","Asia","Western Asia"],
  ["050","BD","Bangladesh","Dhaka","Asia","Southern Asia"],
  ["052","BB","Barbados","Bridgetown","Americas","Caribbean"],
  ["112","BY","Belarus","Minsk","Europe","Eastern Europe"],
  ["056","BE","Belgium","Brussels","Europe","Western Europe"],
  ["084","BZ","Belize","Belmopan","Americas","Central America"],
  ["204","BJ","Benin","Porto-Novo","Africa","Western Africa","Cotonou (seat of government)"],
  ["064","BT","Bhutan","Thimphu","Asia","Southern Asia"],
  ["068","BO","Bolivia","Sucre","Americas","South America","La Paz (seat of government)"],
  ["070","BA","Bosnia and Herzegovina","Sarajevo","Europe","Southeast Europe"],
  ["072","BW","Botswana","Gaborone","Africa","Southern Africa"],
  ["076","BR","Brazil","Brasília","Americas","South America","Rio de Janeiro (former)"],
  ["096","BN","Brunei","Bandar Seri Begawan","Asia","South-Eastern Asia"],
  ["100","BG","Bulgaria","Sofia","Europe","Southeast Europe"],
  ["854","BF","Burkina Faso","Ouagadougou","Africa","Western Africa"],
  ["108","BI","Burundi","Gitega","Africa","Eastern Africa"],
  ["116","KH","Cambodia","Phnom Penh","Asia","South-Eastern Asia"],
  ["120","CM","Cameroon","Yaoundé","Africa","Middle Africa"],
  ["124","CA","Canada","Ottawa","Americas","North America"],
  ["132","CV","Cabo Verde","Praia","Africa","Western Africa"],
  ["140","CF","Central African Republic","Bangui","Africa","Middle Africa"],
  ["148","TD","Chad","N'Djamena","Africa","Middle Africa"],
  ["152","CL","Chile","Santiago","Americas","South America"],
  ["156","CN","China","Beijing","Asia","Eastern Asia"],
  ["170","CO","Colombia","Bogotá","Americas","South America"],
  ["174","KM","Comoros","Moroni","Africa","Eastern Africa"],
  ["178","CG","Republic of the Congo","Brazzaville","Africa","Middle Africa"],
  ["188","CR","Costa Rica","San José","Americas","Central America"],
  ["191","HR","Croatia","Zagreb","Europe","Southeast Europe"],
  ["192","CU","Cuba","Havana","Americas","Caribbean"],
  ["196","CY","Cyprus","Nicosia","Europe","Southern Europe"],
  ["203","CZ","Czechia","Prague","Europe","Central Europe"],
  ["180","CD","Democratic Republic of the Congo","Kinshasa","Africa","Middle Africa"],
  ["208","DK","Denmark","Copenhagen","Europe","Northern Europe"],
  ["262","DJ","Djibouti","Djibouti","Africa","Eastern Africa"],
  ["212","DM","Dominica","Roseau","Americas","Caribbean"],
  ["214","DO","Dominican Republic","Santo Domingo","Americas","Caribbean"],
  ["218","EC","Ecuador","Quito","Americas","South America"],
  ["818","EG","Egypt","Cairo","Africa","Northern Africa"],
  ["222","SV","El Salvador","San Salvador","Americas","Central America"],
  ["226","GQ","Equatorial Guinea","Malabo","Africa","Middle Africa"],
  ["232","ER","Eritrea","Asmara","Africa","Eastern Africa"],
  ["233","EE","Estonia","Tallinn","Europe","Northern Europe"],
  ["748","SZ","Eswatini","Lobamba","Africa","Southern Africa","Mbabane (administrative)"],
  ["231","ET","Ethiopia","Addis Ababa","Africa","Eastern Africa"],
  ["242","FJ","Fiji","Suva","Oceania","Melanesia"],
  ["246","FI","Finland","Helsinki","Europe","Northern Europe"],
  ["250","FR","France","Paris","Europe","Western Europe"],
  ["266","GA","Gabon","Libreville","Africa","Middle Africa"],
  ["270","GM","Gambia","Banjul","Africa","Western Africa"],
  ["268","GE","Georgia","Tbilisi","Asia","Western Asia"],
  ["276","DE","Germany","Berlin","Europe","Western Europe"],
  ["288","GH","Ghana","Accra","Africa","Western Africa"],
  ["300","GR","Greece","Athens","Europe","Southern Europe"],
  ["308","GD","Grenada","St. George's","Americas","Caribbean"],
  ["320","GT","Guatemala","Guatemala City","Americas","Central America"],
  ["324","GN","Guinea","Conakry","Africa","Western Africa"],
  ["624","GW","Guinea-Bissau","Bissau","Africa","Western Africa"],
  ["328","GY","Guyana","Georgetown","Americas","South America"],
  ["332","HT","Haiti","Port-au-Prince","Americas","Caribbean"],
  ["340","HN","Honduras","Tegucigalpa","Americas","Central America"],
  ["348","HU","Hungary","Budapest","Europe","Central Europe"],
  ["352","IS","Iceland","Reykjavik","Europe","Northern Europe"],
  ["356","IN","India","New Delhi","Asia","Southern Asia"],
  ["360","ID","Indonesia","Jakarta","Asia","South-Eastern Asia"],
  ["364","IR","Iran","Tehran","Asia","Southern Asia"],
  ["368","IQ","Iraq","Baghdad","Asia","Western Asia"],
  ["372","IE","Ireland","Dublin","Europe","Northern Europe"],
  ["376","IL","Israel","Jerusalem","Asia","Western Asia"],
  ["380","IT","Italy","Rome","Europe","Southern Europe"],
  ["384","CI","Ivory Coast","Yamoussoukro","Africa","Western Africa","Abidjan (economic)"],
  ["388","JM","Jamaica","Kingston","Americas","Caribbean"],
  ["392","JP","Japan","Tokyo","Asia","Eastern Asia"],
  ["400","JO","Jordan","Amman","Asia","Western Asia"],
  ["398","KZ","Kazakhstan","Astana","Asia","Central Asia","Almaty (former)"],
  ["404","KE","Kenya","Nairobi","Africa","Eastern Africa"],
  ["296","KI","Kiribati","South Tarawa","Oceania","Micronesia"],
  ["414","KW","Kuwait","Kuwait City","Asia","Western Asia"],
  ["417","KG","Kyrgyzstan","Bishkek","Asia","Central Asia"],
  ["418","LA","Laos","Vientiane","Asia","South-Eastern Asia"],
  ["428","LV","Latvia","Riga","Europe","Northern Europe"],
  ["422","LB","Lebanon","Beirut","Asia","Western Asia"],
  ["426","LS","Lesotho","Maseru","Africa","Southern Africa"],
  ["430","LR","Liberia","Monrovia","Africa","Western Africa"],
  ["434","LY","Libya","Tripoli","Africa","Northern Africa"],
  ["438","LI","Liechtenstein","Vaduz","Europe","Western Europe"],
  ["440","LT","Lithuania","Vilnius","Europe","Northern Europe"],
  ["442","LU","Luxembourg","Luxembourg","Europe","Western Europe"],
  ["450","MG","Madagascar","Antananarivo","Africa","Eastern Africa"],
  ["454","MW","Malawi","Lilongwe","Africa","Eastern Africa"],
  ["458","MY","Malaysia","Kuala Lumpur","Asia","South-Eastern Asia"],
  ["462","MV","Maldives","Malé","Asia","Southern Asia"],
  ["466","ML","Mali","Bamako","Africa","Western Africa"],
  ["470","MT","Malta","Valletta","Europe","Southern Europe"],
  ["584","MH","Marshall Islands","Majuro","Oceania","Micronesia"],
  ["478","MR","Mauritania","Nouakchott","Africa","Western Africa"],
  ["480","MU","Mauritius","Port Louis","Africa","Eastern Africa"],
  ["484","MX","Mexico","Mexico City","Americas","North America"],
  ["583","FM","Micronesia","Palikir","Oceania","Micronesia"],
  ["498","MD","Moldova","Chișinău","Europe","Eastern Europe"],
  ["492","MC","Monaco","Monaco","Europe","Western Europe"],
  ["496","MN","Mongolia","Ulan Bator","Asia","Eastern Asia"],
  ["499","ME","Montenegro","Podgorica","Europe","Southeast Europe"],
  ["504","MA","Morocco","Rabat","Africa","Northern Africa"],
  ["508","MZ","Mozambique","Maputo","Africa","Eastern Africa"],
  ["104","MM","Myanmar","Naypyidaw","Asia","South-Eastern Asia","Yangon (former)"],
  ["516","NA","Namibia","Windhoek","Africa","Southern Africa"],
  ["520","NR","Nauru","Yaren","Oceania","Micronesia"],
  ["524","NP","Nepal","Kathmandu","Asia","Southern Asia"],
  ["528","NL","Netherlands","Amsterdam","Europe","Western Europe","The Hague (seat of government)"],
  ["554","NZ","New Zealand","Wellington","Oceania","Australia and New Zealand"],
  ["558","NI","Nicaragua","Managua","Americas","Central America"],
  ["562","NE","Niger","Niamey","Africa","Western Africa"],
  ["566","NG","Nigeria","Abuja","Africa","Western Africa","Lagos (former)"],
  ["408","KP","North Korea","Pyongyang","Asia","Eastern Asia"],
  ["807","MK","North Macedonia","Skopje","Europe","Southeast Europe"],
  ["578","NO","Norway","Oslo","Europe","Northern Europe"],
  ["512","OM","Oman","Muscat","Asia","Western Asia"],
  ["586","PK","Pakistan","Islamabad","Asia","Southern Asia"],
  ["585","PW","Palau","Ngerulmud","Oceania","Micronesia"],
  ["591","PA","Panama","Panama City","Americas","Central America"],
  ["598","PG","Papua New Guinea","Port Moresby","Oceania","Melanesia"],
  ["600","PY","Paraguay","Asunción","Americas","South America"],
  ["604","PE","Peru","Lima","Americas","South America"],
  ["608","PH","Philippines","Manila","Asia","South-Eastern Asia"],
  ["616","PL","Poland","Warsaw","Europe","Central Europe"],
  ["620","PT","Portugal","Lisbon","Europe","Southern Europe"],
  ["634","QA","Qatar","Doha","Asia","Western Asia"],
  ["642","RO","Romania","Bucharest","Europe","Southeast Europe"],
  ["643","RU","Russia","Moscow","Europe","Eastern Europe"],
  ["646","RW","Rwanda","Kigali","Africa","Eastern Africa"],
  ["659","KN","Saint Kitts and Nevis","Basseterre","Americas","Caribbean"],
  ["662","LC","Saint Lucia","Castries","Americas","Caribbean"],
  ["670","VC","Saint Vincent and the Grenadines","Kingstown","Americas","Caribbean"],
  ["882","WS","Samoa","Apia","Oceania","Polynesia"],
  ["674","SM","San Marino","City of San Marino","Europe","Southern Europe"],
  ["682","SA","Saudi Arabia","Riyadh","Asia","Western Asia"],
  ["686","SN","Senegal","Dakar","Africa","Western Africa"],
  ["688","RS","Serbia","Belgrade","Europe","Southeast Europe"],
  ["690","SC","Seychelles","Victoria","Africa","Eastern Africa"],
  ["694","SL","Sierra Leone","Freetown","Africa","Western Africa"],
  ["702","SG","Singapore","Singapore","Asia","South-Eastern Asia"],
  ["703","SK","Slovakia","Bratislava","Europe","Central Europe"],
  ["705","SI","Slovenia","Ljubljana","Europe","Central Europe"],
  ["090","SB","Solomon Islands","Honiara","Oceania","Melanesia"],
  ["706","SO","Somalia","Mogadishu","Africa","Eastern Africa"],
  ["710","ZA","South Africa","Pretoria","Africa","Southern Africa","Bloemfontein, Cape Town"],
  ["410","KR","South Korea","Seoul","Asia","Eastern Asia"],
  ["728","SS","South Sudan","Juba","Africa","Middle Africa"],
  ["724","ES","Spain","Madrid","Europe","Southern Europe"],
  ["144","LK","Sri Lanka","Colombo","Asia","Southern Asia","Sri Jayawardenepura Kotte (legislative)"],
  ["729","SD","Sudan","Khartoum","Africa","Northern Africa"],
  ["740","SR","Suriname","Paramaribo","Americas","South America"],
  ["752","SE","Sweden","Stockholm","Europe","Northern Europe"],
  ["756","CH","Switzerland","Bern","Europe","Western Europe"],
  ["760","SY","Syria","Damascus","Asia","Western Asia"],
  ["678","ST","São Tomé and Príncipe","São Tomé","Africa","Middle Africa"],
  ["762","TJ","Tajikistan","Dushanbe","Asia","Central Asia"],
  ["834","TZ","Tanzania","Dodoma","Africa","Eastern Africa","Dar es Salaam (former)"],
  ["764","TH","Thailand","Bangkok","Asia","South-Eastern Asia"],
  ["626","TL","Timor-Leste","Dili","Asia","South-Eastern Asia"],
  ["768","TG","Togo","Lomé","Africa","Western Africa"],
  ["776","TO","Tonga","Nuku'alofa","Oceania","Polynesia"],
  ["780","TT","Trinidad and Tobago","Port of Spain","Americas","Caribbean"],
  ["788","TN","Tunisia","Tunis","Africa","Northern Africa"],
  ["795","TM","Turkmenistan","Ashgabat","Asia","Central Asia"],
  ["798","TV","Tuvalu","Funafuti","Oceania","Polynesia"],
  ["792","TR","Turkey","Ankara","Asia","Western Asia"],
  ["800","UG","Uganda","Kampala","Africa","Eastern Africa"],
  ["804","UA","Ukraine","Kyiv","Europe","Eastern Europe"],
  ["784","AE","United Arab Emirates","Abu Dhabi","Asia","Western Asia"],
  ["826","GB","United Kingdom","London","Europe","Northern Europe"],
  ["840","US","United States","Washington D.C.","Americas","North America"],
  ["858","UY","Uruguay","Montevideo","Americas","South America"],
  ["860","UZ","Uzbekistan","Tashkent","Asia","Central Asia"],
  ["548","VU","Vanuatu","Port Vila","Oceania","Melanesia"],
  ["336","VA","Vatican City","Vatican City","Europe","Southern Europe"],
  ["862","VE","Venezuela","Caracas","Americas","South America"],
  ["704","VN","Vietnam","Hanoi","Asia","South-Eastern Asia"],
  ["887","YE","Yemen","Sana'a","Asia","Western Asia"],
  ["894","ZM","Zambia","Lusaka","Africa","Eastern Africa"],
  ["716","ZW","Zimbabwe","Harare","Africa","Eastern Africa"],
];

/* Spanish: [country, capital?, footnote?]. Capital omitted where it is
   spelled the same as in English. */
const ES = {
  AF: ["Afganistán"],
  AL: ["Albania"],
  DZ: ["Argelia", "Argel"],
  AD: ["Andorra", "Andorra la Vieja"],
  AO: ["Angola"],
  AG: ["Antigua y Barbuda"],
  AR: ["Argentina"],
  AM: ["Armenia", "Ereván"],
  AU: ["Australia"],
  AT: ["Austria", "Viena"],
  AZ: ["Azerbaiyán", "Bakú"],
  BS: ["Bahamas", "Nasáu"],
  BH: ["Baréin"],
  BD: ["Bangladés", "Daca"],
  BB: ["Barbados"],
  BY: ["Bielorrusia"],
  BE: ["Bélgica", "Bruselas"],
  BZ: ["Belice", "Belmopán"],
  BJ: ["Benín", "Porto Novo", "Cotonú (sede del gobierno)"],
  BT: ["Bután", "Timbu"],
  BO: ["Bolivia", "Sucre", "La Paz (sede del gobierno)"],
  BA: ["Bosnia y Herzegovina"],
  BW: ["Botsuana"],
  BR: ["Brasil", "Brasilia", "Río de Janeiro (anterior)"],
  BN: ["Brunéi"],
  BG: ["Bulgaria", "Sofía"],
  BF: ["Burkina Faso", "Uagadugú"],
  BI: ["Burundi"],
  KH: ["Camboya", "Nom Pen"],
  CM: ["Camerún", "Yaundé"],
  CA: ["Canadá"],
  CV: ["Cabo Verde"],
  CF: ["República Centroafricana"],
  TD: ["Chad", "Yamena"],
  CL: ["Chile"],
  CN: ["China", "Pekín"],
  CO: ["Colombia"],
  KM: ["Comoras"],
  CG: ["República del Congo"],
  CR: ["Costa Rica"],
  HR: ["Croacia"],
  CU: ["Cuba", "La Habana"],
  CY: ["Chipre"],
  CZ: ["Chequia", "Praga"],
  CD: ["República Democrática del Congo", "Kinsasa"],
  DK: ["Dinamarca", "Copenhague"],
  DJ: ["Yibuti", "Yibuti"],
  DM: ["Dominica"],
  DO: ["República Dominicana"],
  EC: ["Ecuador"],
  EG: ["Egipto", "El Cairo"],
  SV: ["El Salvador"],
  GQ: ["Guinea Ecuatorial"],
  ER: ["Eritrea"],
  EE: ["Estonia", "Tallin"],
  SZ: ["Esuatini", "Lobamba", "Mbabane (administrativa)"],
  ET: ["Etiopía", "Adís Abeba"],
  FJ: ["Fiyi"],
  FI: ["Finlandia"],
  FR: ["Francia", "París"],
  GA: ["Gabón"],
  GM: ["Gambia"],
  GE: ["Georgia", "Tiflis"],
  DE: ["Alemania", "Berlín"],
  GH: ["Ghana", "Acra"],
  GR: ["Grecia", "Atenas"],
  GD: ["Granada", "Saint George"],
  GT: ["Guatemala", "Ciudad de Guatemala"],
  GN: ["Guinea", "Conakri"],
  GW: ["Guinea-Bisáu", "Bisáu"],
  GY: ["Guyana"],
  HT: ["Haití", "Puerto Príncipe"],
  HN: ["Honduras"],
  HU: ["Hungría"],
  IS: ["Islandia", "Reikiavik"],
  IN: ["India", "Nueva Delhi"],
  ID: ["Indonesia", "Yakarta"],
  IR: ["Irán", "Teherán"],
  IQ: ["Irak", "Bagdad"],
  IE: ["Irlanda", "Dublín"],
  IL: ["Israel", "Jerusalén"],
  IT: ["Italia", "Roma"],
  CI: ["Costa de Marfil", "Yamusukro", "Abiyán (económica)"],
  JM: ["Jamaica"],
  JP: ["Japón", "Tokio"],
  JO: ["Jordania", "Amán"],
  KZ: ["Kazajistán", "Astaná", "Almatý (anterior)"],
  KE: ["Kenia"],
  KI: ["Kiribati", "Tarawa Sur"],
  KW: ["Kuwait", "Ciudad de Kuwait"],
  KG: ["Kirguistán", "Biskek"],
  LA: ["Laos", "Vientián"],
  LV: ["Letonia"],
  LB: ["Líbano"],
  LS: ["Lesoto"],
  LR: ["Liberia"],
  LY: ["Libia", "Trípoli"],
  LI: ["Liechtenstein"],
  LT: ["Lituania", "Vilna"],
  LU: ["Luxemburgo", "Luxemburgo"],
  MG: ["Madagascar"],
  MW: ["Malaui", "Lilongüe"],
  MY: ["Malasia"],
  MV: ["Maldivas"],
  ML: ["Malí"],
  MT: ["Malta", "La Valeta"],
  MH: ["Islas Marshall"],
  MR: ["Mauritania", "Nuakchot"],
  MU: ["Mauricio"],
  MX: ["México", "Ciudad de México"],
  FM: ["Micronesia"],
  MD: ["Moldavia", "Chisináu"],
  MC: ["Mónaco", "Mónaco"],
  MN: ["Mongolia", "Ulán Bator"],
  ME: ["Montenegro"],
  MA: ["Marruecos"],
  MZ: ["Mozambique"],
  MM: ["Birmania", "Naipyidó", "Rangún (anterior)"],
  NA: ["Namibia"],
  NR: ["Nauru"],
  NP: ["Nepal", "Katmandú"],
  NL: ["Países Bajos", "Ámsterdam", "La Haya (sede del gobierno)"],
  NZ: ["Nueva Zelanda"],
  NI: ["Nicaragua"],
  NE: ["Níger"],
  NG: ["Nigeria", "Abuya", "Lagos (anterior)"],
  KP: ["Corea del Norte", "Pionyang"],
  MK: ["Macedonia del Norte", "Skopie"],
  NO: ["Noruega"],
  OM: ["Omán", "Mascate"],
  PK: ["Pakistán"],
  PW: ["Palaos"],
  PA: ["Panamá", "Ciudad de Panamá"],
  PG: ["Papúa Nueva Guinea", "Puerto Moresby"],
  PY: ["Paraguay"],
  PE: ["Perú"],
  PH: ["Filipinas"],
  PL: ["Polonia", "Varsovia"],
  PT: ["Portugal", "Lisboa"],
  QA: ["Catar"],
  RO: ["Rumanía", "Bucarest"],
  RU: ["Rusia", "Moscú"],
  RW: ["Ruanda"],
  KN: ["San Cristóbal y Nieves"],
  LC: ["Santa Lucía"],
  VC: ["San Vicente y las Granadinas"],
  WS: ["Samoa"],
  SM: ["San Marino", "San Marino"],
  SA: ["Arabia Saudí", "Riad"],
  SN: ["Senegal"],
  RS: ["Serbia", "Belgrado"],
  SC: ["Seychelles"],
  SL: ["Sierra Leona"],
  SG: ["Singapur", "Singapur"],
  SK: ["Eslovaquia"],
  SI: ["Eslovenia", "Liubliana"],
  SB: ["Islas Salomón"],
  SO: ["Somalia", "Mogadiscio"],
  ZA: ["Sudáfrica", "Pretoria", "Bloemfontein, Ciudad del Cabo"],
  KR: ["Corea del Sur", "Seúl"],
  SS: ["Sudán del Sur", "Yuba"],
  ES: ["España"],
  LK: ["Sri Lanka", "Colombo", "Sri Jayawardenepura Kotte (legislativa)"],
  SD: ["Sudán", "Jartum"],
  SR: ["Surinam"],
  SE: ["Suecia", "Estocolmo"],
  CH: ["Suiza", "Berna"],
  SY: ["Siria", "Damasco"],
  ST: ["Santo Tomé y Príncipe", "Santo Tomé"],
  TJ: ["Tayikistán", "Dusambé"],
  TZ: ["Tanzania", "Dodoma", "Dar es Salaam (anterior)"],
  TH: ["Tailandia"],
  TL: ["Timor Oriental"],
  TG: ["Togo"],
  TO: ["Tonga", "Nukualofa"],
  TT: ["Trinidad y Tobago", "Puerto España"],
  TN: ["Túnez", "Túnez"],
  TM: ["Turkmenistán", "Asjabad"],
  TV: ["Tuvalu"],
  TR: ["Turquía"],
  UG: ["Uganda"],
  UA: ["Ucrania", "Kiev"],
  AE: ["Emiratos Árabes Unidos", "Abu Dabi"],
  GB: ["Reino Unido", "Londres"],
  US: ["Estados Unidos", "Washington D. C."],
  UY: ["Uruguay"],
  UZ: ["Uzbekistán", "Taskent"],
  VU: ["Vanuatu"],
  VA: ["Ciudad del Vaticano", "Ciudad del Vaticano"],
  VE: ["Venezuela"],
  VN: ["Vietnam", "Hanói"],
  YE: ["Yemen", "Saná"],
  ZM: ["Zambia"],
  ZW: ["Zimbabue"],
};

export const CONTINENTS = ["Africa", "Americas", "Asia", "Europe", "Oceania"];

export const CONTINENT_ES = {
  Africa: "África",
  Americas: "América",
  Asia: "Asia",
  Europe: "Europa",
  Oceania: "Oceanía",
};

export const SUBREGION_ES = {
  "Australia and New Zealand": "Australia y Nueva Zelanda",
  Caribbean: "Caribe",
  "Central America": "América Central",
  "Central Asia": "Asia Central",
  "Central Europe": "Europa Central",
  "Eastern Africa": "África Oriental",
  "Eastern Asia": "Asia Oriental",
  "Eastern Europe": "Europa Oriental",
  Melanesia: "Melanesia",
  "Micronesia": "Micronesia",
  "Middle Africa": "África Central",
  "North America": "América del Norte",
  "Northern Africa": "África del Norte",
  "Northern Europe": "Europa del Norte",
  Polynesia: "Polinesia",
  "South America": "América del Sur",
  "South-Eastern Asia": "Sudeste Asiático",
  "Southeast Europe": "Europa Sudoriental",
  "Southern Africa": "África Austral",
  "Southern Asia": "Asia del Sur",
  "Southern Europe": "Europa del Sur",
  "Western Africa": "África Occidental",
  "Western Asia": "Asia Occidental",
  "Western Europe": "Europa Occidental",
};

export const COUNTRIES = EN.map(([n3, a2, name, cap, cont, sub, alt]) => {
  const es = ES[a2] ?? [];
  return {
    n3,
    a2,
    cont,
    sub,
    name: { en: name, es: es[0] ?? name },
    cap: { en: cap, es: es[1] ?? cap },
    alt: alt ? { en: alt, es: es[2] ?? alt } : null,
    contName: { en: cont, es: CONTINENT_ES[cont] },
    subName: { en: sub, es: SUBREGION_ES[sub] ?? sub },
  };
});

export const BY_A2 = new Map(COUNTRIES.map((c) => [c.a2, c]));

/* Countries whose distant islands would otherwise shrink the mainland to a
   speck: keep only the polygons whose centroid falls inside this box. */
export const MAINLAND = {
  FR: [-5.5, 41, 10, 51.5],
  ES: [-10, 35.4, 4.5, 44.5],
  PT: [-9.6, 36.8, -6, 42.2],
  GB: [-8.8, 49.7, 2.2, 61],
  NL: [3, 50.6, 7.4, 53.7],
  NO: [4, 57.8, 31.5, 71.4],
  US: [-125.2, 23.8, -66.7, 49.6],
  DK: [8, 54.4, 15.3, 57.9],
  EC: [-81.2, -5.2, -75, 1.6],
  CL: [-76, -56.2, -66, -17.4],
  NZ: [166, -47.6, 179.5, -34],
  AU: [112, -44.2, 154.2, -9],
  IT: [6, 35.3, 18.7, 47.2],
};
