// One-shot: pull latin + latin-ext woff2 subsets from Google Fonts into public/fonts
// and emit src/styles/fonts.css so the site never touches a CDN at runtime.
import { writeFile } from "node:fs/promises";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
const API =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..900&family=Nunito:wght@400..800&family=Space+Mono:wght@400;700&display=swap";

const LATIN = "U+0000-00FF";
const LATIN_EXT = "U+0100-02BA";

const css = await (await fetch(API, { headers: { "User-Agent": UA } })).text();
const blocks = css.split("@font-face").slice(1);
const out = [];

for (const block of blocks) {
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1] ?? "";
  const subset = range.startsWith(LATIN)
    ? "latin"
    : range.startsWith(LATIN_EXT)
      ? "latin-ext"
      : null;
  if (!subset) continue;

  const family = /font-family:\s*'([^']+)'/.exec(block)[1];
  const weight = /font-weight:\s*([^;]+);/.exec(block)[1].trim();
  const url = /src:\s*url\(([^)]+)\)/.exec(block)[1];
  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight.replace(/\s+/g, "-")}-${subset}.woff2`;

  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  await writeFile(new URL(`../src/assets/fonts/${slug}`, import.meta.url), bytes);
  console.log(`${slug}  ${(bytes.length / 1024).toFixed(1)} kB`);

  out.push(`@font-face{
  font-family:'${family}';
  font-style:normal;
  font-weight:${weight};
  font-display:swap;
  src:url('../assets/fonts/${slug}') format('woff2');
  unicode-range:${range};
}`);
}

await writeFile(
  new URL("../src/styles/fonts.css", import.meta.url),
  `/* Generated by scripts/fetch-fonts.mjs — self-hosted so the app works offline. */\n${out.join("\n")}\n`,
);
